#!/bin/bash

GOAGENT_HOME=/Applications/goagent-ios.app
PROXY_CONFIG="$GOAGENT_HOME"/goagent-local/proxy.ini
RESTORE_PY="$GOAGENT_HOME"/goagent-local/restore_setting.py
LAUNCHD_PLIST="$GOAGENT_HOME"/goagent-local/org.goagent.local.ios.plist
STOP_LAUNCHD_PLIST="$GOAGENT_HOME"/goagent-local/org.goagent.local.ios.stop.plist
BACKUP_CONFIG=/tmp/proxy.ini.bak
export PYTHONHOME=/Applications/goagent-ios.app/python

function link_pythonlib()
{
    rm -rf /usr/lib/libpython2.7.dylib
    ln -s "$GOAGENT_HOME/python/lib/libpython2.7.dylib" /usr/lib
}

function change_permissions()
{
    chown -R root:wheel "$GOAGENT_HOME"
    chmod 6755 "$GOAGENT_HOME"/goagent-ios_
    chmod 6756 "$GOAGENT_HOME"/authrunner
}

function try_restore_setting()
{
    if [ -e "$BACKUP_CONFIG" ];then
        echo "restore proxy.ini"
        "$PYTHONHOME/bin/python" "$RESTORE_PY" "$BACKUP_CONFIG"
    fi
}

function start_launchd_task()
{
    rm -rf /Library/LaunchDaemons/org.goagent.local.ios.plist
    rm -rf /Library/LaunchDaemons/org.goagent.local.ios.stop.plist
    ln -s "$LAUNCHD_PLIST" /Library/LaunchDaemons
    ln -s "$STOP_LAUNCHD_PLIST" /Library/LaunchDaemons

    mkdir -p /var/mobile/goagent
    touch /var/mobile/goagent/stop

    chown -R mobile /var/mobile/goagent

    launchctl load "$LAUNCHD_PLIST"
    launchctl load "$STOP_LAUNCHD_PLIST"
}

function copy_certs()
{
    cp -f "$GOAGENT_HOME/goagent-local/CA.crt" /etc/ssl/certs/GOAGENT_CA.crt
    cp -f "$GOAGENT_HOME/goagent-local/CA.key" /etc/ssl/certs/GOAGENT_CA.key
}

function flush_springboard()
{
    sudo -u mobile uicache
}

change_permissions
link_pythonlib
try_restore_setting
start_launchd_task
echo "copy certs"
copy_certs
flush_springboard
