#!/bin/bash

GOAGENT_HOME=/Applications/goagent-ios.app
PROXY_CONFIG="$GOAGENT_HOME"/goagent-local/proxy.ini
RESTORE_PY="$GOAGENT_HOME"/goagent-local/restore_setting.py
LAUNCHD_PLIST="$GOAGENT_HOME"/goagent-local/org.goagent.local.ios.plist
BACKUP_CONFIG=/tmp/proxy.ini.bak
export PYTHONHOME=/Applications/goagent-ios.app/python

function change_permissions()
{
    chown -R root:wheel "$GOAGENT_HOME"
    chmod 6755 "$GOAGENT_HOME"/goagent-ios
    chmod 6756 "$GOAGENT_HOME"/authrunner
    mv "$GOAGENT_HOME"/goagent-ios "$GOAGENT_HOME"/goagent-ios_
    mv "$GOAGENT_HOME"/goagent-ios.sh "$GOAGENT_HOME"/goagent-ios
}

function try_restore_setting()
{
    if [ -e "$BACKUP_CONFIG" ];then
        echo "restore proxy.ini"
        "$PYTHONHOME/bin/python" "$RESTORE_PY" "$BACKUP_CONFIG"
    fi
}

function start_launchd_task()
{
    launchctl load "$LAUNCHD_PLIST"
}

function copy_certs()
{
    cp -f "$GOAGENT_HOME/goagent-local/CA.crt" /etc/ssl/certs/GOAGENT_CA.crt
    cp -f "$GOAGENT_HOME/goagent-local/CA.key" /etc/ssl/certs/GOAGENT_CA.key
}

change_permissions
try_restore_setting
start_launchd_task
echo "copy certs"
copy_certs
