include theos/makefiles/common.mk

BUNDLE_NAME = GoAgentSwitch
GoAgentSwitch_FILES = Switch.x
GoAgentSwitch_FRAMEWORKS = UIKit
GoAgentSwitch_LIBRARIES = flipswitch
GoAgentSwitch_INSTALL_PATH = /Library/Switches

ADDITIONAL_LDFLAGS = -L ./.theos

include $(THEOS_MAKE_PATH)/bundle.mk
